export const SET_AUTHORS = 'SET_AUTHORS';
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const MOVE_AUTHOR_TO_COURSE = 'MOVE_AUTHOR_TO_COURSE';
export const MOVE_AUTHOR_FROM_COURSE = 'MOVE_AUTHOR_FROM_COURSE';
